# 用命令行工具trash-cli来删除文件到~/.local/share/Trash
map DD shell -s trash-put %s

# 使用shift-j和shift-k来切换tab
map J tab_move -1
map K tab_move +1

# View the output of shell command until you press ENTER
map ! console shell -w%space

# 快捷使用ripgrep
map <c-g> console shell -w%space rg -i ""

# 自定义脚本限制预览文件大小
set preview_script ~/.config/ranger/preview_size_check.sh

